### ISSUE TITLE
Set up scaffolding for project

### ISSUE THREAD

**Issue by adamilyas** [hajimss/chatbot#1]
@hajimss set up scaffolding for project:

Create 1 endpoint:

POST /chat
Which receives a req with a message and to return a response with a reply message

**Comment by hajimss** [comment]
Noted. Currently at the phase of setting up the main python file with the machine learning algorithm. For the backend management, I will be utilising Flask to deal with the POST APIs and return a response (product of the chatbot machine learning algorithm) to the frontend.

Here is the rough template of the function that I have in mind:
"""
@route.app('/chat', methods=["POST"])
def chat():
    <request body is passed to the machine learning algorithm and the algorithm will return the chatbot 
    response>
    response = {
    'body' = "Hello There"
    }
    return response
"""

**Comment by adamilyas** [comment]
Done. Pleae update tthe documentation whaat is the url of the endpoint so that I can use
